[package]
name = "rjsdb"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
regex = "1.10.6"
serde = { version = "1.0.205", features = ["derive"] }
